import { JetBrains_Mono } from "next/font/google";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import "./globals.css";

import Navbar from "@/components/Navbar";


const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"] ,
  weight:["100",'200',"300","400","500","600","700","800"],
  variable:"--font-jetbrainsMono"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
